export const enum DataQueryKeys {
  CLIENTS = 'clients',
  DASHBOARD = 'dashboard',
  FAVORITE_METERS = 'favoriteMeters',
  GROUPS = 'groups',
  LOCATIONS = 'locations',
  MEASUREMENTS = 'measurements',
  MEASUREMENT_INFO = 'measurementInfo',
  METERING_POINT_TYPES = 'meteringPointTypes',
  OPTIONS = 'options',
  PERIODIC_ALARM_LIST = 'periodicAlarmList',
  PERIODIC_ALARM_DETAILS = 'periodicAlarmDetails',
  TENANTS = 'tenants',
  USER = 'user',
}
