name: Publish Production Image

on:
  workflow_dispatch:
    branches:
      - main
      - master
    inputs:
      tag:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets: inherit

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-image-webapp:
    name: Publish Production Image webapp
    runs-on: arc-md

    steps:
      - name: Build and publish production image
        uses: Rhino-Energy/github-actions/.github/actions/javascript-monorepo@main
        with:
          aws-ecr-repo: "rhino-webapp"
          docker-file-path: "apps/webapp/dockerProduction.Dockerfile"
          tag: ${{ inputs.tag }}
          version: ${{ inputs.version }}
          aws-region: ${{ vars.aws_region }}
          aws-iam-role: ${{ secrets.aws_iam_role }}
          aws-ecr-account-id: ${{ vars.aws_ecr_account_id }}
