on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

name: Release PR Flow
run-name: "Build for production & Push Image"

jobs:
  create-release-tag:
    name: Create/Update Release PR
    runs-on: arc-sm
    outputs:
      webapp-release-tag-name: ${{ steps.release.outputs['webapp--tag_name'] }}
      webapp-release-version: ${{ steps.release.outputs['webapp--major'] }}.${{ steps.release.outputs['webapp--minor'] }}.${{ steps.release.outputs['webapp--patch'] }}
      webapp-release-created: ${{ steps.release.outputs['webapp--releases_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ contains(github.ref_name, 'hotfix-') && github.ref_name ||  github.event.repository.default_branch }}

      - name: Print Release Please outputs
        run: |
          echo "tag_name: ${{ steps.release.outputs['webapp--tag_name'] }}"
          echo "major: ${{ steps.release.outputs['webapp--major'] }}"
          echo "minor: ${{ steps.release.outputs['webapp--minor'] }}"
          echo "patch: ${{ steps.release.outputs['webapp--patch'] }}"
          echo "version: ${{ steps.release.outputs['webapp--major'] }}.${{ steps.release.outputs['webapp--minor'] }}.${{ steps.release.outputs['webapp--patch'] }}"
          echo "release_created: ${{ steps.release.outputs['webapp--release_created'] }}"
          echo "all outputs: ${{ toJson(steps.release.outputs) }}"
  publish-image-webapp:
    name: Publish Production Image webapp
    runs-on: arc-md
    needs: create-release-tag
    if: ${{ needs.create-release-tag.outputs.webapp-release-created == 'true' }}
    outputs:
      tag: ${{ needs.create-release-tag.outputs.webapp-release-tag-name }}
      version: ${{ needs.create-release-tag.outputs.webapp-release-version }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Print Create release tag outputs
        run: |
          echo "Incoming tag name: ${{ needs.create-release-tag.outputs.webapp-release-tag-name }}"
          echo "Incoming tag name: ${{ needs.create-release-tag.outputs.webapp-release-version }}"
          echo "Incoming tag name: ${{ needs.create-release-tag.outputs.webapp-release-created }}"

      - name: Build and publish image
        uses: Rhino-Energy/github-actions/.github/actions/javascript-monorepo@main
        with:
          aws-ecr-repo: "rhino-webapp"
          docker-file-path: "apps/webapp/dockerProduction.Dockerfile"
          tag: ${{ needs.create-release-tag.outputs.webapp-release-tag-name }}
          version: ${{ needs.create-release-tag.outputs.webapp-release-version }}
          aws-region: ${{ vars.aws_region }}
          aws-iam-role: ${{ secrets.aws_iam_role }}
          aws-ecr-account-id: ${{ vars.aws_ecr_account_id }}
