on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

name: Release PR Flow
run-name: "Build for production & Push Image"

jobs:
  create-release-tag:
    name: Create/Update Release PR
    runs-on: self-hosted
    outputs:
      webapp-release-tag-name: ${{ steps.release.outputs['apps/webapp--tag_name'] }}
      webapp-release-version: ${{ steps.release.outputs['apps/webapp--major'] }}.${{ steps.release.outputs['apps/webapp--minor'] }}.${{ steps.release.outputs['apps/webapp--patch'] }}
      webapp-release-created: ${{ steps.release.outputs['apps/webapp--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ contains(github.ref_name, 'hotfix-') && github.ref_name ||  github.event.repository.default_branch }}
      - name: print filter output
        run: echo '${{ toJSON(steps.release.outputs) }}'

  publish-image-webapp:
    name: Publish Production Image webapp
    runs-on: self-hosted
    needs: create-release-tag
    if: ${{ needs.create-release-tag.outputs.webapp-release-created == 'true' }}
    outputs:
      tag: ${{ needs.create-release-tag.outputs.webapp-release-tag-name }}
      version: ${{ needs.create-release-tag.outputs.webapp-release-version }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Build and publish image
        uses: Rhino-Energy/github-actions/.github/actions/javascript-monorepo@main
        with:
          aws-ecr-repo: "rhino-webapp"
          docker-file-path: "apps/webapp/Dockerfile"
          tag: ${{ needs.create-release-tag.outputs.webapp-release-tag-name }}
          version: ${{ needs.create-release-tag.outputs.webapp-release-version }}
          aws-region: ${{ vars.aws_region }}
          aws-iam-role: ${{ secrets.aws_iam_role }}
          aws-ecr-account-id: ${{ vars.aws_ecr_account_id }}
